config/routes.rb
Rails.application.routes.draw do
  get "home/index"
  root to: "home#index"
  resources :countries
  resources :users, only: [:new, :create, :edit, :update, :index, :destroy]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/login', to: "sessions#login"
  post '/login', to: "sessions#create"
  post '/logout', to: "sessions#destroy"
  get '/logout', to: "sessions#destroy"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/country.rb
class Country < ApplicationRecord

  def self.feature_collection
    features = []

    find_each { |f| features << JSON.parse(f.as_geojson) }

    "{\"type\":\"FeatureCollection\",\"features\":#{features.to_json}}"
  end

  def as_geojson
    properties = as_json.except("created_at", "updated_at", "geojson").delete_if{|k,v| v.nil?}

    "{\"type\":\"Feature\",\"geometry\":#{geojson.squish},\"properties\":#{properties.to_json}}"
  end

end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/countries_controller.rb
class CountriesController < ApplicationController
  before_action :check_login, except: :show
  before_action :set_country, only: %i[ show edit update destroy ]

  # GET /countries or /countries.json
  def index
    @countries = Country.all.order(:name)
    gon.countries_geo = @countries.feature_collection
  end

  # GET /countries/1 or /countries/1.json
  def show
  end

  # GET /countries/new
  def new
    @country = Country.new
  end

  # GET /countries/1/edit
  def edit
  end

  # POST /countries or /countries.json
  def create
    @country = Country.new(country_params)

    respond_to do |format|
      if @country.save
        format.html { redirect_to @country, notice: "Country was successfully created." }
        format.json { render :show, status: :created, location: @country }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @country.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /countries/1 or /countries/1.json
  def update
    respond_to do |format|
      if @country.update(country_params)
        format.html { redirect_to @country, notice: "Country was successfully updated." }
        format.json { render :show, status: :ok, location: @country }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @country.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /countries/1 or /countries/1.json
  def destroy
    @country.destroy
    respond_to do |format|
      format.html { redirect_to countries_url, notice: "Country was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_country
      @country = Country.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def country_params
      params.require(:country).permit(:name, :iso_a3, :geojson)
    end

    def check_login
      unless !!session[:user_id]
        respond_to do |format|
          format.html { redirect_to login_path, notice: "Only registered can access this page" }
        end
      end
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @countries = Country.all
    gon.countries_geo = @countries.feature_collection
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    @user = User.find_by(username: params[:username])

    if !!@user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to countries_path
    else
      message = "Username / Password wrong"
      redirect_to login_path, notice: message
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :check_admin
  before_action :set_user, only: %i[ edit update destroy ]
  def index
    @users = User.all.order(:username)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path
    else
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to users_url, notice: "User was successfully updated." }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:username, :password, :is_admin)
  end

  def check_admin
    unless !!session[:user_id] && User.find(session[:user_id]).is_admin
      respond_to do |fmt|
        fmt.html { redirect_to '/', notice: "Only admins can access this page" }
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def logged_in?
    !!session[:user_id]
  end

  def current_user
    @current_user ||= User_find(session[:user_id]) if logged_in?
  end
end

app/helpers/countries_helper.rb
module CountriesHelper
end

app/views/countries/_form.html.erb
<%= form_with(model: country) do |form| %>

  <div class="col-md-8">
    <div class='mb3'>
        <%= form.label :name, class:"form-label" %>
      <div class='row'>
        <div class='col'>
          <%= form.text_field :name, class:"form-control" %>
        </div>
      </div>
    </div>

    <div class='mb3'>
        <%= form.label :iso_a3, class:"form-label" %>
      <div class='row'>
        <div class='col'>
          <%= form.text_field :iso_a3, class:"form-control" %>
        </div>
      </div>
    </div>

    <div class='mb3'>
        <%= form.label :geojson, class:"form-label" %>
      <div class='row'>
        <div class='col'>
          <%= form.text_area :geojson, class:"form-control" %>
        </div>
      </div>
    </div>

    <% if country.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(country.errors.count, "error") %> prohibited this country from being saved:</h2>

        <ul>
          <% country.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="mb3">
      <div class="actions">
        <%= form.submit 'Sumbit', class: "btn btn-warning" %>
      </div>
    </div>
  </div>
<% end %>

app/views/countries/edit.html.erb
<h3>Editing <%= @country.name %></h3>

<%= render 'form', country: @country %>

<%= link_to 'Show', @country %> |
<%= link_to 'Back', countries_path %>

app/views/countries/index.html.erb
<p id="notice"><%= notice %></p>

<h3>Countries</h3>


<div id="mapid">
</div>

<table class="table">
  <thead  class="table-dark">
    <tr>
      <th>Name</th>
      <th>Population</th>
      <th>GDP</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @countries.each do |country| %>
      <tr>
        <td><%= country.name %></td>
        <td><%= country.pop_est %></td>
        <td><%= country.gdp_md_est %></td>
        <td><%= link_to 'Show', country, class: "btn btn-primary" %></td>
        <td><%= link_to 'Edit', edit_country_path(country), class: "btn btn-warning" %></td>
        <td><%= link_to 'Destroy', country, method: :delete, class: "btn btn-danger", data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Back', home_index_path, class: "btn btn-primary" %>
<%= link_to 'New Country', new_country_path, class: "btn btn-secondary" %>

app/views/countries/new.html.erb
<h3>New Country</h3>

<%= render 'form', country: @country %>

<%= link_to 'Back', countries_path %>

app/views/countries/show.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
  <div class="col-md-8">
    <h3><%= @country.name %></h3>
    <table class="table table-striped">
      <thead  class="table-dark">
        <tr>
          <th>Attribute</th>
          <th>Value</th>
        </tr>
      </thead>

      <tbody>
        <% @country.attributes.keys.each do |attribute| %>
          <tr>
            <td><%= attribute.humanize %></td>
            <td><%= @country.attributes[attribute].to_s %></td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <%= link_to 'Edit', edit_country_path(@country) %> |
    <%= link_to 'Back', countries_path %>
  </div>
</div>

app/views/home/index.html.erb
<section class="py-5 text-center container">
  <div class="row py-lg-5">
    <div id="mapid"></div>
    <p>Click on the map to get European Countries information.</p>
    <p><small><%= link_to 'Login', login_path %></small></p>
  </div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MapDiscovery</title>
    <%= Gon::Base.render_data %>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div id="navbar">
      <div class="bg-dark p-4">
        <h5 class="text-white h4">Map Discovery</h5>
        <span class="text-muted">Explore geographic data.</span>
      </div>
    </div>
    <main>
      <%= yield %>
    </main>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <div class="col-md-8">
    <div class='mb3'>
        <%= form.label :username, class:"form-label" %>
      <div class='row'>
        <div class='col'>
          <%= form.text_field :username, class:"form-control" %>
        </div>
      </div>
    </div>

    <div class='mb3'>
        <%= form.label :password, class:"form-label" %>
      <div class='row'>
        <div class='col'>
          <%= form.password_field :password, class:"form-control" %>
        </div>
      </div>
    </div>

    <div class='mb3'>
        <%= form.label :is_admin, class:"form-label" %>
      <div class='row'>
        <div class='col'>
          <%= form.check_box :is_admin  %>
        </div>
      </div>
    </div>

    <div class="mb3">
      <div class="actions">
        <%= form.submit 'Sumbit', class: "btn btn-primary" %>
      </div>
    </div>
  </div>
<% end %>

app/views/users/edit.html.erb
<h3>Editing <%= @user.username %></h3>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h3>Users</h3>

<table class="table">
  <thead  class="table-dark">
    <tr>
      <th>Username</th>
      <th>Admin</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.username %></td>
        <td><%= user.is_admin %></td>
        <td><%= link_to 'Edit', edit_user_path(user), class: "btn btn-warning" %></td>
        <td><%= link_to 'Destroy', user, method: :delete, class: "btn btn-danger", data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Back', home_index_path, class: "btn btn-primary" %>
<%= link_to 'New User', new_user_path, class: "btn btn-secondary" %>

app/views/users/new.html.erb
<h3>New User</h3>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>